# Generated by Django 5.1.2 on 2024-10-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_patient_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='dob',
        ),
    ]
