# Generated by Django 5.1.2 on 2024-11-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='contact_information',
            field=models.CharField(default='Not Provided', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
