# Generated by Django 5.1.2 on 2024-11-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_patient_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_information',
            field=models.CharField(blank=True, default='Not provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('', 'Select Sex'), ('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
