# Generated by Django 5.1.3 on 2024-11-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_patient_middle_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='contact_information',
            new_name='phone_number',
        ),
    ]
