# Generated by Django 5.1.3 on 2024-11-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_rename_contact_information_patient_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospital_assigned',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
