# Generated by Django 5.1.3 on 2024-11-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(default='consultation', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=100),
        ),
    ]
