# Generated by Django 5.1.3 on 2024-12-03 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_alter_doctor_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.OneToOneField(help_text='Each patient can have only one appointment.', on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='doctor.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
