# Generated by Django 5.1.3 on 2024-12-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_alter_appointment_patient_alter_patient_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(max_length=50),
        ),
    ]
